name: Documentation

on:
  push:
    branches:
      - 'main'
    tags: '*'
    paths-ignore:
      - '.zenodo.json'
      - '.github/workflows/benchmark.yml'
      - '.github/workflows/ci.yml'
      - '.github/workflows/CompatHelper.yml'
      - '.github/workflows/TagBot.yml'
      - 'benchmark/**'
      - 'utils/**'
  pull_request:
    paths-ignore:
      - '.zenodo.json'
      - '.github/workflows/benchmark.yml'
      - '.github/workflows/ci.yml'
      - '.github/workflows/CompatHelper.yml'
      - '.github/workflows/TagBot.yml'
      - 'benchmark/**'
      - 'utils/**'
  workflow_dispatch:

# Cancel redundant CI tests automatically
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    uses: "SciML/.github/.github/workflows/documentation.yml@v1"
    secrets: "inherit"
